package lv.kristine;

public class TestExceptionHandling {

	public static void main(String[] args) {

		try {
			int number1 = 0;
			int number2 = 10;
			int result = number2 / number1;
			System.out.println(result);
		} catch (Exception varOfException) {
			System.out.println("check code in try catch block: "
					+ varOfException);
		}

		
		try{
		int[]myNumbers = {5,7,2,64,21,89};
		System.out.println(myNumbers[2]);
		}catch(Exception e){
			System.out.println("Error in array");
		}finally{
			System.out.println("The try catch block is finished.");
		}
	}

}
